# Generated by Django 5.2 on 2025-04-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('locked_in', models.BooleanField(default=False)),
            ],
        ),
    ]
