# Generated by Django 5.2 on 2025-05-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_contact_delete_customuser_alter_task_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentUserIndex', models.IntegerField(default=999)),
            ],
        ),
    ]
