# Generated by Django 5.2 on 2025-05-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_currentuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Guest', max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(default='#ff4646', max_length=7)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('locked_in', models.BooleanField(default=True)),
            ],
        ),
    ]
