# Generated by Django 5.2 on 2025-05-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0005_taskstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstatus',
            old_name='taskstatus',
            new_name='status',
        ),
    ]
